### ISSUE TITLE
different file size is ignored if for some reason md5 of two files is identical

### ISSUE THREAD

**Issue by kabu0001** [adrianlopezroche/fdupes#182] opened 2024-02-14 20:50 UTC
As the title says, i get erratic duplicate results if for some reason (dont ask me how that could happen) two files have the same name, same md5 hash but completely different sizes.

**Comment by stvoidit** [comment] 2024-05-05 07:15
Today I found this program and compiled it from the source code. I was very surprised to see the use of md5, although it seems that it is quite difficult to catch a real collision for files.
In this case, it is more strange that the file size is not checked - it seems more critical than choosing an algorithm for hashing.

**Comment by jbruchon** [comment] 2024-05-05 13:36
The hash is a fast exclusion feature. It is not used to determine if files are the same; it is used to determine if files are different. A hash collision does not cause a false positive duplicate result.

**Comment by adrianlopezroche** [comment] 2024-07-16 07:01
The program does check file sizes. Absent some bug I'm not aware of files with different sizes are treated as being different regardless of what their MD5 hash may be. In fact, a file won't even be hashed at all unless at least one other file having the same size has been found. I'm closing this as unable to reproduce with the information provided.

**Closed by adrianlopezroche** 2024-07-16 07:01 UTC
