### ISSUE TITLE
google code issues were not migrated to github

### ISSUE THREAD

**Issue by sandrotosi** [adrianlopezroche/fdupes#40] opened 2015-12-17 07:11 UTC
Hey! any reason why the gcode issues where not migrated to github? I have a lot of debian bugs linked to upstream issues, and I'd like to point them to github now, but I would prefer not to create all the issues by hand (as that would mean I'd lose some of the replies/information)

could you import them please? thanks!

**Comment by jbruchon** [comment] 2015-12-17 14:09
I just reviewed the `fdupes` issues list on Google Code. The vast majority of them have either been fixed in current master or are not actual bugs in the software.

**Comment by sandrotosi** [comment] 2015-12-17 14:18
can you list them explicitly?

**Comment by jbruchon** [comment] 2015-12-17 14:25
I'm not the maintainer, so I'm not listing anything. A casual glance at the Google Code issues list shows that most "issues" are just feature requests, requests for improvements that are already part of the algorithm, misunderstandings regarding third-party modifications that were never present in upstream in the first place, or other questions that don't have any bugs to report. I see very little value in copying these into the current issue lists. It is possible that the mentioned Debian bug reports should be closed; if they are bona fide bugs confirmed to still be present in master, they should be manually added here so they can be fixed and propagated downstream.

**Comment by sandrotosi** [comment] 2015-12-17 14:30
it doesnt matter if you are the maintainer or not; and by listing I mean "write down a list here of what exactly issues are fixed in master and what others are no longer a bug"

did you check any of the debian bugs, and their related issues on gcode to say that the c an be closed? if not, maybe dont state "The vast majority of them have either been fixed in current master or are not actual bugs in the software." if you havent actually looked into the matter.

thanks

**Comment by sandrotosi** [comment] 2015-12-20 14:10
I used https://github.com/sandrotosi/google-code-issues-migrator to migrate only the issues I have debian bugs linked to (FTR Google Code issue IDs: "18 24 19 4 8 3 2 1 22 31") to a temporary GH repo, and then forwarded here with https://github-issue-mover.appspot.com/ (i couldnt do in a single step as ./migrateissues.py expects the destination prj to be owned by the GH user you're logging in with)

**Comment by adrianlopezroche** [comment] 2015-12-23 18:25
Thanks.

**Closed by adrianlopezroche** 2015-12-23 18:25 UTC
