### ISSUE TITLE
Can't type return when inside the fdupes terminal screen

### ISSUE THREAD

**Issue by Sciamano72** [adrianlopezroche/fdupes#174] opened 2023-03-03 14:16 UTC
Hello,
I have installed fdupes in my Linux Mint 21.1 installation using ubuntu repositories (I've always done it this way). Package version 1:2.1.2-1build1.
Now, whenever I launch fdupes I can never choose what file to keep because I can't send the enter command: I hit the return key (which works perfectly when "outside" fdupes) but nothing happens. Same thing happens when I try to exit the program: I type 'exit' but can't send the command because the return key is not working.
WTH?

**Comment by adrianlopezroche** [comment] 2023-03-06 05:04
I'm not sure what it could be. To fdupes the enter key is just a newline character, so I figure it should work unless maybe there's something wrong with the _terminfo_ mappings or the latest ncurses library on Linux Mint 21.1? I'm using an older version of Mint, so I can't test it myself. You could try running fdupes with the `--plain` parameter as a workaround while the problem is discovered.

**Comment by adrianlopezroche** [comment] 2023-03-07 15:44
I know very little about terminfo so I'm afraid I can't help there. I'm hoping someone will see this who can help, but I think your best option will be to file a bug report with the Linux Mint folks and see if they can figure it out.

**Comment by Sciamano72** [comment] 2023-03-07 16:04
I understand. At least I can use the `--plain` parameter and still make fdupes work.
Anyway I will file a bug report @ Linux Mint and see what happens. I'm startled by the fact that it looks like no one else is affected by this problem, though!

**Comment by adrianlopezroche** [comment] 2024-07-16 07:02
Closing this as unable to reproduce.

**Closed by adrianlopezroche** 2024-07-16 07:02 UTC
